# Generated by Django 5.0.3 on 2024-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_Group',
            field=models.CharField(choices=[('1', 'A Rh+'), ('2', 'B Rh+'), ('3', '0 Rh+'), ('4', 'A Rh-'), ('5', 'B Rh-'), ('6', '0 Rh-'), ('7', 'AB Rh+'), ('8', 'AB Rh-')], default='1', max_length=20),
        ),
    ]
