# Generated by Django 5.0.3 on 2024-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_Group',
            field=models.CharField(choices=[('1', 'A Rh+'), ('2', 'B Rh+'), ('3', '0 Rh+'), ('4', 'A Rh-'), ('5', 'B Rh-'), ('6', '0 Rh-'), ('7', 'AB Rh+'), ('8', 'AB Rh-')], default='1', max_length=20, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DateOfBirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
