# Generated by Django 5.0.3 on 2024-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_blood_group_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='IsVisible',
            field=models.BooleanField(default=True),
        ),
    ]
