# Generated by Django 5.0.3 on 2024-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='PriceUnit',
            field=models.IntegerField(verbose_name='Price Unit'),
        ),
    ]
