# Generated by Django 5.0.3 on 2024-04-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
    ]
