# Generated by Django 5.0.3 on 2024-04-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_appointmentdate'),
        ('bill', '0002_alter_bill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
