# Generated by Django 5.0.3 on 2024-04-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('AppointmentDate', models.DateField()),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
            ],
        ),
    ]
