# Generated by Django 5.0.3 on 2024-04-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_appointmentdate'),
        ('doctor', '0005_alter_doctor_dateofbirth_alter_doctor_department_and_more'),
        ('patient', '0004_alter_patient_blood_group_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='IsVisible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='AppointmentDate',
            field=models.DateTimeField(verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='DoctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='PatientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient', verbose_name='Patient'),
        ),
    ]
