# Generated by Django 5.0.3 on 2024-04-27 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateOfBirth', models.DateField(verbose_name='Date of Birth')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('Phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('IsVisible', models.BooleanField(default=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accountant',
            },
        ),
    ]
