# Generated by Django 5.0.3 on 2024-04-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_table'),
        ('doctor', '0002_alter_doctor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='department.department'),
        ),
    ]
