# Generated by Django 5.0.3 on 2024-04-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_name_alter_department_priceunit'),
        ('doctor', '0004_remove_doctor_address_remove_doctor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DateOfBirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='department.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.TextField(verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Languages',
            field=models.CharField(max_length=300, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(max_length=11, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Salary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specializations',
            field=models.CharField(max_length=300, verbose_name='Specializations'),
        ),
    ]
