# Generated by Django 5.0.3 on 2024-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_dateofbirth_alter_doctor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='IsVisible',
            field=models.BooleanField(default=True),
        ),
    ]
