# Generated by Django 5.0.3 on 2024-04-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Medicinde', models.CharField(max_length=30)),
                ('Remark', models.TextField()),
                ('Advice', models.TextField()),
                ('Appointment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
    ]
