# Generated by Django 5.0.3 on 2024-04-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('IssuedDate', models.DateField()),
                ('Amount', models.IntegerField()),
                ('IsPaid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('PriceUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Blood_Group', models.CharField(max_length=3)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Specializations', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('Languages', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Blood_Group', models.CharField(max_length=3)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=500)),
                ('AppointmentDate', models.DateField()),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.doctor')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Medicinde', models.CharField(max_length=30)),
                ('Remark', models.CharField(max_length=30)),
                ('Advice', models.CharField(max_length=30)),
                ('Appointment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
