# Generated by Django 5.0.3 on 2024-04-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Surname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Surname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.BooleanField()),
                ('Blood_Group', models.CharField(max_length=3)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
