# Generated by Django 5.0.3 on 2024-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_patient_userid_remove_doctor_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='IsAccountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Blood_Group',
            field=models.CharField(choices=[('1', 'A Rh+'), ('2', 'B Rh+'), ('3', '0 Rh+'), ('4', 'A Rh-'), ('5', 'B Rh-'), ('6', '0 Rh-')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Blood_Group',
            field=models.CharField(choices=[('1', 'A Rh+'), ('2', 'B Rh+'), ('3', '0 Rh+'), ('4', 'A Rh-'), ('5', 'B Rh-'), ('6', '0 Rh-')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Languages',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specializations',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Blood_Group',
            field=models.CharField(choices=[('1', 'A Rh+'), ('2', 'B Rh+'), ('3', '0 Rh+'), ('4', 'A Rh-'), ('5', 'B Rh-'), ('6', '0 Rh-')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Advice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Remark',
            field=models.TextField(),
        ),
    ]
